#!/usr/bin/env bash

echo "Building Container"
docker build -t megadetector-onnx .

echo "Downloading MDv5a"
mkdir -p models
wget -q -c https://github.com/microsoft/CameraTraps/releases/download/v5.0/md_v5a.0.0.pt -O models/md_v5a.0.0.pt

echo "Converting MDv5a 640x640"
docker run --rm -v $(pwd)/models:/home/workspace/models megadetector-onnx python -m yolov5.export --img-size 640 --img-size 640 --include onnx --weights models/md_v5a.0.0.pt
mv models/md_v5a.0.0.onnx models/md_v5a.0.0-640x640.onnx

echo "Converting MDv5a 720x1080"
docker run --rm -v $(pwd)/models:/home/workspace/models megadetector-onnx python -m yolov5.export --img-size 720 --img-size 1080 --include onnx --weights models/md_v5a.0.0.pt
mv models/md_v5a.0.0.onnx models/md_v5a.0.0-720x1080.onnx


echo "Downloading MDv5b"
wget -q -c https://github.com/microsoft/CameraTraps/releases/download/v5.0/md_v5b.0.0.pt -O models/md_v5b.0.0.pt

echo "Converting MDv5b 640x640"
docker run --rm -v $(pwd)/models:/home/workspace/models megadetector-onnx python -m yolov5.export --img-size 640 --img-size 640 --include onnx --weights models/md_v5b.0.0.pt
mv models/md_v5b.0.0.onnx models/md_v5b.0.0-640x640.onnx

echo "Converting MDv5b 720x1080"
docker run --rm -v $(pwd)/models:/home/workspace/models megadetector-onnx python -m yolov5.export --img-size 720 --img-size 1080 --include onnx --weights models/md_v5b.0.0.pt
mv models/md_v5b.0.0.onnx models/md_v5b.0.0-720x1080.onnx